channels:
  - conda-forge
dependencies:
  - python=3.9
  - zeromq
  - pyzmq
  - pyyaml
  - trollsift
  - configobj
  - netifaces
  - s3fs>=2022.8.2
  - pip
  - git
  - pip:
    - posttroll
    - pytroll-collectors
