channels:
  - conda-forge
  - eumetsat
dependencies:
  - python=3.11
  - zeromq
  - pyzmq
  - pyyaml
  - trollsift
  - configobj
  - netifaces
  - satpy
  - pyresample
  - pykdtree
  - trollimage
  - rasterio
  - pyorbital
  - gdal
  - h5py
  - h5netcdf
  - public-decomp-wt
  - netcdf4
  - paramiko
  - scp
  - fsspec
  - dpath
  - toolz
  - configobj
  - shapely
  - donfig
  - pip
  - scipy
  - fasteners
  - numcodecs
  - asciitree
  - git
  - pip:
    - posttroll
    - git+https://github.com/pytroll/trollflow2.git@99d4a6b9a6bbad8f04dc7874a56b393c0eea5dbf
