channels:
  - conda-forge
  - eumetsat
dependencies:
  - python=3.13
  - zeromq
  - pyzmq
  - pyyaml
  - trollsift
  - configobj
  - netifaces
  - satpy
  - pyresample>=1.33.0
  - pykdtree
  - trollimage
  - rasterio
  - pyorbital
  - gdal
  - h5py
  - h5netcdf
  - hdf5plugin
  - public-decomp-wt
  - netcdf4
  - paramiko
  - scp
  - fsspec
  - dpath
  - toolz
  - configobj
  - shapely
  - donfig
  - pip
  - scipy
  - fasteners
  - numcodecs
  - asciitree
  - bottleneck
  - git
  - pip:
      - posttroll
      - pyninjotiff
      - trollflow2>=0.17.0
